### ISSUE TITLE
Cop table layout is broken

### ISSUE THREAD

**Issue by okuramasafumi** [rubocop/docs.rubocop.org#11]
<img width="821" alt="スクリーンショット 2022-11-06 14 24 23" src="https://user-images.githubusercontent.com/1012014/200155603-661fc1c2-9b66-4af4-881f-b5d2fa5c1d29.png">

The table layout for cop description looks broken. I couldn't find a commit that introduced this change, but I remember a few month ago it was displayed correctly as a table.

**Comment by koic** [comment]
This issue is a dup with https://github.com/rubocop/rubocop/issues/11153.

**Comment by koic** [comment]
RuboCop 1.39 has been released. Please see the latest docs. Thank you.
