### ISSUE TITLE
Documentation for rubocop-rspec 3.1 missing

### ISSUE THREAD

**Issue by dmke** [rubocop/docs.rubocop.org#26]
The documentation website is missing the latest documentation for rubocop-rspec 3.1 (release PR https://github.com/rubocop/rubocop-rspec/pull/1963). In particular, the docs for `RSpec/StringAsInstanceDoubleConstant` are missing.

I'm not sure if this is the right place for this issue. If not, feel free to transfer it to the appropriate repository.

---

Edit: As a workaround, browsing the API docs works as well, albeit not as convenient:

https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/StringAsInstanceDoubleConstant.

**Comment by bbatsov** [comment]
Opening an issue here is fine. @bquorning @Darhazer Please, take a look when you can.

**Comment by bquorning** [comment]
Thank you for raising the issue @dmke. I’ll be fixing it right away.

**Comment by bquorning** [comment]
Here you go @dmke: https://docs.rubocop.org/rubocop-rspec/3.1/cops_rspec.html#rspecstringasinstancedoubleconstant

**Comment by dmke** [comment]
Thank you very much!
